kafka:
  bootstrap:
    servers: localhost:9092  # Используем существующую Kafka из первого сервиса
  topic:
    metrics: metrics
  consumer:
    group:
      id: clickhouse-consumer-group
    auto_offset_reset: earliest

clickhouse:
  url: jdbc:clickhouse://localhost:8123/default  # ClickHouse из своего контейнера
  username: default
  password: ""
  table:
    metrics: system_metrics
  batch:
    size: 1000
    interval_ms: 5000